### ISSUE TITLE
Basic data structures

### ISSUE THREAD

**Issue by k00ni** [k00ni/learn#1]
* [x] data set (tuple)
* [x] array
* [x] queue
* [x] stack
* [x] hash table

**Comment by jumper320** [comment]
Data set (tuple): A tuple represents an amount of attributes, therefore a data set. In a spreadsheet, a tuple is represented by a row.

**Comment by jumper320** [comment]
Array: An array is a container object, which hold a fixed amount of values of a single type. These values can be accessed by an index.

**Comment by jumper320** [comment]
Queue: A queue is a special kind of abstract data types in which the instances are always hold in one specific order. The main-operations are to enqueue, to attach an instance to the queue-end, and to dequeue, to detach at the queue-front. FIRST-IN-FIRST-OUT (FIFO) data structure.

**Comment by jumper320** [comment]
Stack: A stack is an abstract data type, which serves the collection of elements. There are two main operations: push, which adds an element to the collection, and pop, which removes the latest added eement. LIFO -> Last in, First out.

**Comment by k00ni** [comment]
@jumper320: Would you extend your **array** description with information about dynamic arrays, for instance in PHP or JavaScript? Your points:

* values of single type
* fixed amount of values

*may* not apply there.

**Comment by jumper320** [comment]
Supplement array:

In comparison to the static array the dynamic arrays able to change size during program execution. Therefore when a programmer doesn't know how much data an array will hold, he uses a dynamic array.

An array only holds objects of a specific type,, but it is not assigned to one data type ( e.g it can hold integer as well as string).

**Comment by jumper320** [comment]
Hash table:

Hash function + array

The hash function generates a number from a given key and stores the value, which is linked to the key, to the index position with the same number as the generated number.

**Comment by k00ni** [comment]
:+1:

**Comment by k00ni** [comment]
If you think, you got all the info necessary, click to the button "Close issue". This way i can see, which topics you covered.
