### ISSUE TITLE
Research common Javascript design pattern

### ISSUE THREAD

**Issue by jumper320** [k00ni/learn#10]
* [x] What is a design pattern?
* [x] What is a anti pattern?
* [ ] Describe two basic patterns.

**Comment by jumper320** [comment]
A design pattern is a gerneral repeatable solution to a commonly occurring problem in software design. It is a description or template for how to solve a problem in many different situations.

**Comment by jumper320** [comment]
An anti pattern is a commonly occurring solution to a problem that generates decidedly negative consequences. It is a bad description or template to solve a problem.

**Comment by k00ni** [comment]
:+1:

**Comment by jumper320** [comment]
```javascript

var Zahl = class Zahl {
  constructor(value) {
	  //This condition checks if value is not a number. If so, the 
	  //statement will end the construction of the object 
	  if (typeof value !== "number"){
		  throw "Error: No number"
	  }
	  this.value = value;
  }
	getValue () {
        return this.value;
    };
	
	addiereMit (zahl2) {
		return this.getValue()+zahl2.getValue();
	};
	subtrahiereVon (zahl2) {
		return this.getValue()-zahl2.getValue();
	};
	multipliziereMit (zahl2) {
		return this.getValue()*zahl2.getValue();
	};
	teileDurch (zahl2) {
		return this.getValue()/zahl2.getValue();
	};
};

var z1 = new Zahl(5);
var z2 = new Zahl(10);

console.log(z1.addiereMit(z2));
console.log(z1.subtrahiereVon(z2));
console.log(z1.multipliziereMit(z2));
console.log(z1.teileDurch(z2));
```

**Comment by jumper320** [comment]
I am not able or to be more precise I have no idea how to create the function istZahl() and to check the value before the construction of the object. I worked my way around it with the condition in the constructor.

**Comment by k00ni** [comment]
Your class looks good for now, because you reached your goal. In case i provide a string instead of a number, an error should be thrown. That's what we wanted to achieve.

**Comment by k00ni** [comment]
I forgot, the third task is not finished yet.

**Comment by jumper320** [comment]
I have trouble understanding two patterns. I did research design patterns an read about creational patterns, structural patterns, behavioral patterns and concurrency patterns but I don't understand one of the many patterns. Or did I misunderstood the third question?

**Comment by k00ni** [comment]
> Or did I misunderstood the third question?

No, the objective was to describe two patterns, but as you said, you currently don't understand one, therefore let this task be and move to the one we talked about. No problem, you dont back off, you just delay the execution :)
