### ISSUE TITLE
Basic data types

### ISSUE THREAD

**Issue by k00ni** [k00ni/learn#2]
* [x] string
* [x] integer
* [x] float
* [x] double
* [x] boolean

Bonus:
* [x] What is the difference between a 32 bit and a 64 bit data type?

**Comment by jumper320** [comment]
String:

Traditionally a string is a sequence of characters, which are constant or variable.

**Comment by jumper320** [comment]
Integer:

An integer is a numeric data type, which is comprised of (surprise, surprise) integers. This data type is finite and can vary in length and can also be in the negative, depending on the system.

**Comment by jumper320** [comment]
Float:

The float data type can handle decimal numbers. The float is finite and can only handle seven decimal numbers ( Java 32 bit).

Double:
Is the same as the float data type, but it can handle until 15 decimal numbers.

**Comment by jumper320** [comment]
Boolean:

A boolean has most times only two states: true or false, 1 or 0.

**Comment by jumper320** [comment]
Bonus: The only difference between a 32 bit and a 64 bit data type is the memory size.

**Comment by k00ni** [comment]
@jumper320: Your description for boolean is incorrect. If you haven't a quantum computer, a boolean has *always* only two states.

Additionally, can you be more precise about the memory size? (bonus)

**Comment by k00ni** [comment]
Btw. your additions with "finite" are implicit and could be removed, because a computer cant store infinity :)

**Comment by jumper320** [comment]
A 64 bit data type is 2⁶⁴ bit big and a 32 bit data type is only 2³² bit big.

**Comment by k00ni** [comment]
:+1:
