### ISSUE TITLE
Variables and constants

### ISSUE THREAD

**Issue by k00ni** [k00ni/learn#5]
* [x] What are variables? 
* [x] What are constants?
* [x] What is the difference between them?

**Comment by jumper320** [comment]
What are variables?

Variables are used to store information to be referenced and manipulated in a computer program.

It i helpful to think of variables as containers that hold information. Their sole purpose is to label and store data in memory.

**Comment by jumper320** [comment]
What are constants?

Constants are fixed values.

**Comment by jumper320** [comment]
What is the difference between them?

Constants are established at the beginning of the program and can't be changed during the execution. Variables are established during the execution or and can be changed during it.
