### ISSUE TITLE
Operators

### ISSUE THREAD

**Issue by k00ni** [k00ni/learn#6]
* [x] What are operators? (for instance +, -,...) 
* [x] List major operators (4)
* [x] How operators are used? (Are there rules how to use them?)

Bonus:
* [x] List two more operators

**Comment by jumper320** [comment]
What are operators?

An operator is an object which is capable of manipulating one or two operands.

**Comment by jumper320** [comment]
List major operators 

+ - * / != ++

**Comment by jumper320** [comment]
How are operators used?

Generally to manipulate operands. Operators cannot manipulate operators (e.g. +-+) and constants.
