### ISSUE TITLE
Control structures

### ISSUE THREAD

**Issue by k00ni** [k00ni/learn#7]
* [x] What are control structures, like if-elseif-else? What is there purpose? 
* [x] How can i connect multiple conditions?
* [x] What is a switch-case structure?

Bonus:
* [x] What is the difference between switch-case and if-elseif-else structures?

**Comment by jumper320** [comment]
What are control structures? What is their purpose?

A control structure is a block of programming that analyzes variables and chooses a direction in which to go/ what to make based on given parameters.

**Comment by jumper320** [comment]
How can I connect multiple conditions?

You can combine else's with other if's -> else-if. But if one condition is true it will stop comparing and run the statement.

**Comment by jumper320** [comment]
What is a switch-case structure?

Unlike if-then and if-then-else statements, the switch statement can have a number of possible execution paths.

The if-else ladder is type of strict condition check, while switch case is of type jump value catching.
