### ISSUE TITLE
Loops

### ISSUE THREAD

**Issue by k00ni** [k00ni/learn#8]
* [x] What is a for-loop?
* [x] What is a while-loop?
* [x] What is a do-while-loop?
* [x] What is a foreach loop?

Bonus:
* [x] How to stop/break out of a loop?

**Comment by jumper320** [comment]
What is a for-loop?

A for-loop is a repetition control structure that allows you to efficiently write a loop that needs to execute a specific number of times.

**Comment by jumper320** [comment]
What is a while-loop?

A while-loop in C programming repeatedly executes a target statement as long a given condition is true.

**Comment by jumper320** [comment]
What is a do-while-loop?

A do-while-loop is similar to a while loop, except for the fact that it is guaranteed to be executed at least one time before checking the statement.

**Comment by jumper320** [comment]
What is a for each loop?

For each (or foreach) is a top-controlled control flow statement for traversing items in a collection. Foreach is usually used in place of a standard for statement.

**Comment by jumper320** [comment]
How to stop/break out of a loop?

Either kick your pc real hard or throw it out of a window.

The more cost efficient method would be to simply stop by the command stop or return when your condition is fulfilled.
