### ISSUE TITLE
Write a Javascript function to calculate +, -, * and /

### ISSUE THREAD

**Issue by k00ni** [k00ni/learn#9]
Whats the status here?

**Comment by jumper320** [comment]
I've finished the function on friday and it's working. However I wanted to solve a syntax error until I've noticed that this not possible. It annoys me that the operator must be a string with the " ". I want to write e.g. function( 2, 2, +) but I have to write function( 2, 2, "+").

**Comment by k00ni** [comment]
Please paste the code here.

**Comment by jumper320** [comment]
var gru = function(zahl1, zahl2, operator){

	do{

	var go = true;
	var tmp;

	if (typeof zahl1 == "number" && typeof zahl2 == "number" && typeof operator == "string"){
		
		if (operator == "+"){

			return zahl1 + zahl2;

		}
		else if (operator == "-"){

			return zahl1 - zahl2;

		}
		else if (operator == "/"){

			if( zahl2 != 0){

				return zahl1 / zahl2;
			}else return "Scherzkeks";

		}
		else if (operator == "*"){

			return zahl1 * zahl2;

		} else return "Bitte einen der gueltigen Operatoren angeben: +, -, /, *."
		
	}else if (typeof operator == "number"){
		
		if(typeof zahl1 == "string"){

			tmp= operator;
			operator= zahl1;
			zahl1=tmp;
			go=false;

		}else if (typeof zahl2 == "string"){

			tmp= operator;
			operator= zahl2;
			zahl2=tmp;
			go=false;

		}else return "Bitte den Operator als String angeben";

	}

		
	}while(go == false);
};

**Comment by k00ni** [comment]
Some questions:

* [ ] Why using a do-while loop?
* [ ] Did you test edge cases?
  * [ ] zahl1 or zahl2 are strings/boolean/object...
  * [ ] division by 0

**Comment by k00ni** [comment]
* [ ] Can you give my an example how to "automatically" check, if the function does what you expect? Maybe some code afterwards which checks that.

**Comment by jumper320** [comment]
Why using a do-while loop?

The code must be executed at least once and a head-controlled loop wouldn't allow that.

**Comment by jumper320** [comment]
Did you test edge cases?

strings/boolean/object.... :

Yes, but I only test if zahl1 or zahl2 are strings, in which case I can swap operator and number.

division by 0: 

Yes with the block: if(zahl2 != 0)

**Comment by k00ni** [comment]
> **Why using a do-while loop?** The code must be executed at least once and a head-controlled loop wouldn't allow that. The purpose is, after an operator and one of numbers are swapped, to run again and calculate this time.

Why would i swap a parameter? Do you mean you replace the value of zahl2 with the one of the operator and vice versa? I am not getting the idea behind your function. My guess is, that the loop is unnecessary.

**Comment by jumper320** [comment]
This is my current code:




var testParameters = function( numb1, numb2, operator){

	//This function checks if the user gave thr right parameters

	if (typeof operator != "string" && typeof operator != "number" && ( typeof numb1 != "number" || typeof numb2 != "number" ) ) {

		return "Bitte den Operator als String angeben und die Zahlen als Integer";

	}

	else if (typeof operator == "string" && ( typeof numb1 == "string"|| typeof numb2 == "string" ) ){
	
		return "Bitte den Operator als String angeben und die Zahlen als Integer";
	}

	else if (typeof numb1 == "number" && typeof numb2 == "number" && typeof operator == "string"){

		return 1;

	}

	else if (typeof operator == "number"){
	
		if(typeof numb1 == "string" && typeof numb2 == "number"){
		
			return 2;

		}else if (typeof numb2 == "string" && typeof numb1 == "number"){

			return 3;

		}else return "Bitte den Operator als String angeben und die Zahlen als Integers";

	}
	return -1;

};


var calculateTwoNumbers = function(zahl1, zahl2, operator){

	//This function does the actual calculation
		
		if (operator == "+"){

			return zahl1 + zahl2;

		}
		else if (operator == "-"){

			return zahl1 - zahl2;

		}
		else if (operator == "/"){

			if( zahl2 != 0){

				return zahl1 / zahl2;
		
			}else return "Scherzkeks";

		}
		else if (operator == "*"){

			return zahl1 * zahl2;

		} else return "Bitte einen der gueltigen Operatoren angeben: +, -, /, *.";

};

var calculate =	function ( numb1, numb2, operator){

	// This functions is called to calculate and it calls the other two functions to test and to calculate.
	// case2 and case3 are there to swap the operator and one of the numbers , if user didn't input these 
	// in the forseen order.

	var numb3 = numb1;
	var numb4 = numb2;
	var operator1 = operator;


	var decide;


	decide = testParameters(numb3, numb4, operator1);

	while(decide !== 1){

		var tmp;

		switch(decide){

			case 1:

				return calculateTwoNumbers( numb3, numb4, operator1);

			case 2:

				tmp= operator1;
				operator1= numb3;
				numb3= tmp;
				break;

			case 3:

				tmp= operator1;
				operator1= numb4;
				numb4= tmp;
				break;

			default:

				throw decide;
		}

		decide = testParameters(numb3, numb4, operator1);
	}

	return calculateTwoNumbers( numb3, numb4, operator1);

};

**Comment by jumper320** [comment]
Why would I swap a parameter?

The function only works if you give it a number, a number and a string. E.g. gru( 4,4,"+"). 

But what happens when the user puts the parameters in incorrectly? E.g. gru("+",4,4).
The function doesn't work then. So I check if the users put the parameters in correctly, if not, I will swap the parameters and then run the code again to calculate this time.

**Comment by k00ni** [comment]
Ah cool, you want to make the function more robust against invalid user input. That's a good approach and in general a good way. But, you have to be sure, that the program acts as expected, always, even for the absurdest data you put into. As an user, i wouldn't expect such a behavior. I would look into the function head, get the parameter list and put my data in accordingly. We should talk about this case later on.

Nevertheless, for now, try to change this function to be more strict with the parameter. First parameter `zahl1` has to be a number, second a number and so on. Check that before you compute anything. Include checks for bool, object and array please. Also check, that the user used one of the following operators +, -, / and *.

Instead of returning an error message, you could try using an exception and try / catch constructs. That's advanced stuff, but maybe what you are looking for. Try [exception handling](http://eloquentjavascript.net/1st_edition/chapter5.html).

After you are sure, you got the right data, compute the result accordingly and return it.

**Btw.:** Please [highlight](https://help.github.com/articles/creating-and-highlighting-code-blocks/) your code, for better readability.

**Comment by k00ni** [comment]
How is the state her?

**Comment by jumper320** [comment]
```javascript
//This function checks if the correct parameters are given, the correct operators and if someone tries to divide by 0
var testParameters = function( numb1, numb2, operator){


	
	if (typeof numb1 !== "number"){
		throw "Bitte ersten Operanten als Zahl eingeben!"
	}
	if (typeof numb2 !== "number"){
		throw "Bitte ersten Operanten als Zahl eingeben!"
	}
	if (typeof operator !== "string"){
		throw "Bitte Operation als Zeichen (+,-,*,/) eingeben!"
	}
	//Here we check if the varaible operator is one of the valid operators
	if( operator !== "+" && operator !== "-" && operator !== "*" && operator !== "/" ){
		throw "Operation muss eines von {+,-,*,/} sein."
	}
	//Here the condition checks if someone tries the impossible 
	if( operator == "/" && numb2 == 0 ){
		throw "Scherzkeks";
	}

}

// fixParameters swaps the parameters if someone has put them in the incorrect oder
var fixParameters = function(parameters){

	//Checks if one of the parameters is not from the type it should be
	if ( !(typeof parameters[0] == "number" && typeof parameters[1] == "number" && typeof parameters[2] == "string") ){
		var tmp;

		//If numb1 is a string it'll swap with the operator and the operator swaps its number with numb2 and
		//numb2 with numb1. This is important for the case of subtraction or division before e.g. dividend and divisor are swapped 
		if (typeof parameters[0] == "string"){
			tmp = parameters[0];
			parameters[0] = parameters[1];
			parameters[1] = parameters[2];
			parameters[2] = tmp;
		}

		//if numb2 is a string it'll swap with the operator
		else if (typeof parameters[1] == "string"){
			tmp = parameters[2];
			parameters[2] = parameters[1];
			parameters[1] = tmp;
		}
	}
	return parameters;
};

//This function does the actual caltulation
var calculateTwoNumbers = function(zahl1, zahl2, operator){
		
	if (operator == "+"){
		return zahl1 + zahl2;
	}
	else if (operator == "-"){
		return zahl1 - zahl2;
	}
	else if (operator == "/"){
		return zahl1 / zahl2;
	}
	else if (operator == "*"){
		return zahl1 * zahl2;
	}
};

//This function is used by the user and is given the parameters.
//It'll only call the other functions and return the result of the calculation.
var calculate =	function ( numb1, numb2, operator){

	try{
		testParameters(numb1, numb2, operator);
	}
	catch( excpetion ){
		parameters = fixParameters([numb1, numb2, operator]);
		numb1 = parameters[0];
		numb2 = parameters[1];
		operator = parameters[2];
	}
	testParameters(numb1, numb2, operator);
	return calculateTwoNumbers( numb1, numb2, operator);
};
```

**Comment by k00ni** [comment]
:+1:
